import type { LegalDocument } from './types';

export const aiAddendum: LegalDocument = {
  title: 'AI Litigation Intelligence Services Addendum',
  lastUpdated: 'December 15, 2025',
  content: `
This AI Litigation Intelligence Services Addendum ("AI Addendum") supplements and forms part of the TrialBase Terms of Use ("Terms"). If there is a conflict between this AI Addendum and the Terms, this AI Addendum controls only with respect to the AI Services defined below.

## 1. Definitions

**1.1** "AI Services" means TrialBase's AI-powered litigation intelligence functionality that ingests, processes, analyzes, and transforms unstructured legal, medical, and case-related materials into structured insights, summaries, timelines, narratives, drafts, and other outputs.

**1.2** "Customer" means the entity or person accepting these Terms for access to AI Services, including (as applicable) a law firm, business, or individual consumer.

**1.3** "Authorized Users" means Customer's employees, contractors, legal assistants, paralegals, attorneys, and other users Customer permits to access the AI Services under Customer's account, subject to these Terms.

**1.4** "Customer Data" means any data, documents, text, images, audio, video, exhibits, records, transcripts, pleadings, police reports, medical records, and other content submitted to or made available to the AI Services by or on behalf of Customer (including data from connected integrations, if enabled).

**1.5** "Outputs" means any results generated by the AI Services based on Customer Data, including summaries, structured fields, issue spotting, timelines, medical treatment chronologies, damages summaries, liability/casation analyses, draft demand packages, settlement narratives, deposition/trial preparation materials, and citation-backed work product.

**1.6** "Order Form" means a mutually agreed ordering document referencing the AI Services (including pricing, usage limits, term, and support tier), if applicable.

**1.7** "Customer Content" means all data, documents, files, text, transcripts, medical records, prompts, inputs, outputs, and other materials submitted to or processed through the Services by or on behalf of Customer.

## 2. Scope of AI Services

**2.1 Purpose.** The AI Services are designed to help attorneys, legal assistants, and end users augment legal workflows by reducing manual review time, increasing case velocity, and improving consistency and quality across litigation work product. The AI Services may ingest and analyze documents including medical records, deposition transcripts, police reports, and case documents to in support of:
- identifying key facts, timelines, and inconsistencies;
- summarizing injuries, treatments, and damages;
- surfacing liability arguments and causation theories;
- quantifying economic and non-economic damages; and
- generating demand packages, settlement narratives, and litigation-ready summaries.

**2.2 No Replacement of Professional Judgment.** Customer acknowledges and agrees that:
- Outputs are assistive and do not replace attorney judgment, case strategy, or professional review;
- Customer is solely responsible for reviewing Outputs for accuracy, completeness, legal sufficiency, and fitness for use; and
- Customer remains fully responsible for all filings, advice, communications, negotiations, and decisions.

**2.3 AI Services Characteristics.** Customer acknowledges and agrees that AI Services use evolving technologies that may produce outputs that are unpredictable, inaccurate, offensive, or otherwise unsatisfactory. TrialBase will periodically modify, update, or enhance the AI Services or models to improve performance, add capabilities, or address security concerns.

## 3. Not Legal or Medical Advice

**3.1 No Legal Advice.** Outputs are for informational and workflow support purposes only and do not constitute legal advice. TrialBase is not a law firm, does not provide legal services, and does not create an attorney-client relationship.

**3.2 No Medical Advice.** Outputs that reference medical records are not medical advice or diagnosis. Customer is responsible for clinical interpretation and any medical conclusions.

## 4. Customer Responsibilities

**4.1 Authority and Rights in Customer Data.** Customer represents and warrants it has (and will maintain) all rights, consents, permissions, and authority necessary to provide Customer Data to TrialBase and to allow TrialBase to process Customer Data to provide the AI Services.

**4.2 Use Restrictions.** Customer will not (and will not allow Authorized Users to):
- use AI Services for unlawful purposes, deceptive practices, or to violate others' rights;
- submit content that Customer is not legally permitted to share;
- attempt to reverse engineer, extract, or infer model parameters, source code, or underlying system prompts;
- use Outputs as the sole basis for legal or medical decisions without appropriate professional review;
- engage in model extraction, modify, adapt, translate, reverse engineer, decompile, disassemble or convert any elements of the AI Services or otherwise attempt to discover the source code, algorithms, logic; or
- use the AI Services in any high-risk, critical infrastructure or safety-critical applications or where errors or failures could reasonably be expected to lead to death, personal injury, or physical, financial, or reputational harm.

**4.3 Human Review Requirement (Best Practice).** Customer agrees to implement reasonable review procedures (including attorney review where applicable) before relying on Outputs for demands, settlement communications, pleadings, or trial materials. Customer remains solely responsible for reviewing, validating, and verifying the Outputs prior to relying on them or using them in any decision.

**4.4 Compliance and Oversight.** Customer is solely responsible for complying with all applicable laws and regulations related to its use of AI technologies, including Data Protection Laws, consumer protection laws, and disclosure requirements regarding the use of automated systems. Customer shall implement appropriate safeguards and oversight mechanisms when deploying AI Services, particularly when such services interact directly with the Customer's customers. Customer shall notify TrialBase of any observed malfunction, inaccuracy, or unintended behaviour of the AI Services.

## 5. Data Processing, Confidentiality, and Security

**5.1 Confidentiality of Customer Data.** TrialBase will treat Customer Data as confidential and will not disclose Customer Data except:
- as necessary to provide the AI Services and support;
- to TrialBase's vendors/subprocessors under confidentiality obligations;
- to comply with law, legal process, or governmental request; or
- as otherwise permitted by the Privacy Policy or these Terms.

**5.2 Security.** TrialBase will maintain administrative, technical, and physical safeguards designed to protect Customer Data against unauthorized access, disclosure, alteration, and destruction.

**5.3 Subprocessors.** TrialBase may use subprocessors to provide portions of the AI Services (e.g., hosting, analytics, model infrastructure). TrialBase will require subprocessors to maintain appropriate confidentiality and security obligations consistent with this AI Addendum. A list of Subprocessors can be obtained upon request sent to support@trialbase.com. AI Services may use or be dependent upon third party AI models, systems and services, and the providers of those AI models, systems and services may require that TrialBase impose additional terms and conditions upon the Customer, before the Customer may make use of those AI Services.

**5.4 Retention and Deletion.** TrialBase will retain Customer Data as described in the Platform settings, Order Form, or applicable policies. Customer may request deletion consistent with legal retention requirements, billing integrity, dispute handling, and backup/archival limitations.

## 6. Sensitive Data and Regulated Information

**6.1 Protected Health Information (PHI).** Unless TrialBase has expressly agreed in writing (e.g., via a Business Associate Agreement, "BAA"), Customer agrees not to submit PHI in a manner that makes TrialBase a "Business Associate" under HIPAA. If a BAA is executed, HIPAA-specific terms will control for PHI.

**6.2 Consumer Personal Information.** Customer is responsible for providing any notices and obtaining any consents required under applicable privacy laws (including CCPA/CPRA where applicable) for Customer's submission and processing of personal information through the AI Services.

**6.3 High-Risk Uses.** Customer will not use the AI Services in a manner that violates applicable professional responsibility rules, court orders, protective orders, confidentiality obligations, or privacy laws.

## 7. Output Characteristics; Citations; Defensibility

**7.1 Citation-Backed Outputs.** Where the AI Services provide citations, references, or links to source excerpts, those are provided to support Customer's verification workflow. Customer acknowledges citations may not capture all relevant context and may require review of original documents.

**7.2 No Guarantee of Accuracy.** Due to the probabilistic nature of AI and variable source quality, Outputs may contain errors, omissions, or misinterpretations. Customer is solely responsible for verifying Outputs against source materials.

**7.3 Customer-Controlled Judgment.** Customer retains full control over legal strategy and judgment and is responsible for how Outputs are used or relied upon.

## 8. Ownership and License

**8.1 Customer Data.** As between the parties, Customer retains all right, title, and interest in and to Customer Data.

**8.2 TrialBase Technology.** TrialBase retains all right, title, and interest in and to the Platform, AI Services, models, software, and underlying technology, including improvements and derivatives, subject only to the limited licenses granted herein.

**8.3 License to Process Customer Data.** Customer grants TrialBase a non-exclusive license to host, reproduce, process, transmit, and otherwise use Customer Data solely to provide, maintain, secure, and improve the AI Services, comply with law, and enforce these Terms.

**8.4 Outputs.** Customer may use Outputs for Customer's internal business purposes and litigation matters. TrialBase does not claim ownership of Customer's Outputs as used within Customer's matters; however, TrialBase retains ownership in the AI Services and systems used to generate Outputs. The Customer's rights to use outputs may depend upon the AI Services in question, and the Customer shall abide by any restrictions on such use that are notified by TrialBase to the Customer from time to time.

**8.5 Feedback.** Feedback is licensed to TrialBase as provided in the Terms.

## 9. Use of Customer Content; No Model Training

**9.1 Customer Content.** As between the parties, Customer retains all right, title, and interest in and to all data, documents, files, text, transcripts, medical records, prompts, inputs, outputs, and other materials submitted to or processed through the Services by or on behalf of Customer ("Customer Content").

**9.2 Use for Improvement.** TrialBase may use Customer Data and Outputs in de-identified and/or aggregated form to improve reliability, security, and performance of the AI Services, including evaluation, debugging, and quality assurance. TrialBase will implement measures designed to reduce risk of re-identification when using de-identified/aggregated data.

**9.3 Permitted Use.** TrialBase may use Customer Content solely as necessary to provide, maintain, secure, and support the Services for Customer in accordance with this Agreement, including for generating Outputs requested by Customer, preventing abuse or security incidents, and complying with applicable law.

**9.4 Aggregated and De-Identified Data.** Notwithstanding the foregoing, TrialBase may use aggregated and de-identified data derived from use of the Services (that does not identify Customer or any individual and cannot reasonably be re-identified) for analytics, benchmarking, service optimization, and business operations, provided such data is not used to train or improve AI models.

**9.5 No Model Training.** TrialBase must not without the Customer's prior consent use the Customer Data, or authorise or enable any third party to use the Customer Data, to train, reinforce, tune, enhance, test or validate any AI model.

**9.6 Third-Party AI Providers.** TrialBase shall contractually require any third-party AI or infrastructure providers that process Customer Content on TrialBase's behalf to comply with the restrictions set forth in this Section.

## 10. Fees and Billing (AI Services)

**10.1 Fees.** Customer will pay fees for AI Services as described on the Platform, in an Order Form, or in a published pricing page, as applicable.

**10.2 Usage-Based Charges.** AI Services may be priced based on usage (e.g., document volume, pages, minutes, tokens, storage, seats). Customer is responsible for usage incurred by Authorized Users. The use of AI Services is subject to fair use limitations defined in the Fair Usage Policy, and TrialBase shall endeavour to provide notification to the Customer when AI Services usage reaches at least 80% of the monthly fair use limit.

**10.3 Auto-Renewal (If Applicable).** If AI Services are offered via subscription, the subscription and automatic renewal provisions in the Terms apply, including clear disclosures, affirmative consent, and cancellation parity.

## 11. Warranties; Disclaimers (AI Services)

**11.1 Limited Warranty.** TrialBase warrants it will provide the AI Services in a professional and workmanlike manner consistent with generally accepted industry standards for similar services.

**11.2 Disclaimer.** EXCEPT AS EXPRESSLY PROVIDED, THE AI SERVICES AND OUTPUTS ARE PROVIDED "AS IS" AND "AS AVAILABLE.". TRIALBASE DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND ANY WARRANTY THAT OUTPUTS WILL BE ACCURATE, COMPLETE, ERROR-FREE, OR SUITABLE FOR ANY PARTICULAR USE OR OUTCOME. All Outputs are provided "as is" and with "all faults." TrialBase makes no representations or warranties of any kind regarding the Outputs, including, without limitation, any warranty as to accuracy, completeness, timeliness, truthfulness, or fitness for a particular purpose.

**11.3 Third-Party Materials.** TrialBase is not responsible for errors caused by Customer Data quality, third-party systems, or external sources.

## 12. Indemnification (AI Services)

**12.1 Customer Indemnity.** Customer will indemnify and hold harmless TrialBase from claims arising out of (a) Customer Data; (b) Customer's or Authorized Users' misuse of the AI Services; or (c) Customer's violation of law or third-party rights (including privacy/confidentiality obligations). Customer shall also indemnify, defend, and hold harmless TrialBase and its affiliates, and their respective officers, directors, employees, and agents, from and against any and all claims, damages, losses, liabilities, costs, and expenses (including reasonable attorneys' fees) arising out of or related to any allegation.

**12.2 TrialBase IP Indemnity (Optional Enterprise Term).** If provided in an Order Form, TrialBase will defend Customer against third-party claims that the AI Services infringe intellectual property rights, subject to customary exclusions (Customer modifications, combination with non-TrialBase items, misuse, and use after notice to stop).

## 13. Limitation of Liability (AI Services)

The limitation of liability provisions in the Terms apply to this AI Addendum. Without limiting the foregoing, TrialBase will not be liable for: (a) decisions made by Customer or counsel; (b) filings, settlement positions, or trial outcomes; (c) reliance on Outputs without professional review; (d) indirect, incidental, consequential, special, or punitive damages to the maximum extent permitted by law; (e) the accuracy, completeness, or appropriateness of any content, recommendation, decision, action, or output generated by the AI Services; (f) any consequence resulting from Customer's implementation of or reliance upon any content, recommendation, decision, action, or output generated by the AI Services; (g) any damage or loss arising from the Customer's failure to review, test, or appropriately oversee the AI Services and their output; or (h) any unintended bias, discrimination, or unfair treatment that may result from the use of AI Services.

## 14. Term; Suspension; Termination (AI Services)

**14.1 Term.** Access to AI Services continues until terminated under the Terms or the applicable Order Form.

**14.2 Suspension.** TrialBase may suspend AI Services for security concerns, suspected fraud, unlawful activity, abuse, or material breach, consistent with the Terms.

**14.3 Effect of Termination.** Upon termination, Customer's right to access AI Services ceases. TrialBase may retain certain data as required for legal compliance, billing integrity, dispute resolution, and backups, consistent with Section 5.4.
`,
};
